"""Constants"""

from math import cos, pi

# Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 960
SCREEN_HALF_WIDTH = SCREEN_WIDTH // 2
SCREEN_HALF_HEIGHT = SCREEN_HEIGHT // 2
SCREEN_TOP_MARGIN = 80
SCREEN_BOTTOM_MARGIN = 80
SCREEN_LEFT_MARGIN = 150
SCREEN_RIGHT_MARGIN = 150

COS_60 = cos(60 * pi / 180)
CELL_SIDE_LENGTH = 70
