"""Constants"""

from math import cos, pi

# Screen
SCREEN_WIDTH = 1900
SCREEN_HEIGHT = 1000
SCREEN_HALF_WIDTH = SCREEN_WIDTH // 2
SCREEN_HALF_HEIGHT = SCREEN_HEIGHT // 2
SCREEN_TOP_MARGIN = 10
SCREEN_BOTTOM_MARGIN = 10
SCREEN_LEFT_MARGIN = 80
SCREEN_RIGHT_MARGIN = 80

# Math
COS_60 = cos(60 * pi / 180)
